name: specs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@master
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
